# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Adam Ballif Pedagogy Blog
email: ballifa@byui.edu
description: >- # this means to ignore newlines until "baseurl:"
 Dr. Adam Ballif holds a Doctor of Musical Arts and a Master of Music degree in clarinet performance from Arizona State University. Dr. Ballif joined the faculty of Brigham Young University-Idaho in 2012. 
baseurl: /adamballifpedagogy # the subpath of your site, e.g. /blog
url: https://adamballif.github.io # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: adamballif
# github_username:  adamballif`

# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
show_excerpts: true
# disqus_shortname: aballif
# searchResultTemplate: '<div><a href="{url}"><h1>{title}</h1></a><span>{date}</span></div>',

# Google Analytics
# google_analytics: G-PPLD9SR428

plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Set which comment system to use
comments:
  # 'disqus' / 'giscus' / 'utterances' are available
  provider:            giscus

# You must install utterances github app before use.(https://github.com/apps/utterances)
# Make sure all variables are set properly. Check below link for detail.
# https://utteranc.es/
# utterances:
#   repo:                "LazyRen/LazyRen.github.io"
#   issue-term:          "pathname"
#   label:               "Comments"
#   theme:               "dark-blue"

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "adamballif/adamballifpedagogy"
  repo-id:             "R_kgDORKk0VQ"
  category:            "General"
  category-id:         "DIC_kwDORKk0Vc4C2H20"
  mapping:             "pathname"
  reaction-enabled:    "1"
  theme:               "dark_dimmed"
  crossorigin:         "anonymous"



plainwhite:
  portfolio_image:  "assets/clarinetclip.jpg"
 # disqus_shortname: aballif
 # sitemap: true
  search: true
  dark_mode: true
  name: Adam Ballif 
  tagline: Pedagogy Blog
  date_format: "%b %-d, %Y"
  # social_links:
   # github: adamsappletech
  navigation:
    - title: "Tags"
      url: "/adamballifpedagogy/categories"
    - title: About
      url: "/adamballifpedagogy/about"
    - title: Subscribe (RSS)
      url: "/adamballifpedagogy/feed.xml"
   #  - title: Podcast
    #   url: "/podcast"
    
   #  - title: Apps
    #   url: "/apps"
    # - title: "About"
    #  url: "/about.markdown"
  condensed_mobile:
    - home
    - post
    - page

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
# remote_theme: mmistakes/minimal-mistakes@4.24.0
# minimal_mistakes_skin: "default" # Choose: default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise# Author information
# show_excerpts: true
#plugins:
 # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
